apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: kekhuay-xyz-com-tls
spec:
  secretName: kekhuay-xyz
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kekhuay.xyz
  dnsNames:
    - kekhuay.xyz
    - www.kekhuay.xyz
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - kekhuay.xyz
          - www.kekhuay.xyz
